<!-- Footer -->
		<footer id="footer">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-5">
						<div class="footer-widget">
							<div class="footer-logo">
								<a href="index.php" class="logo"><img src="" alt=""></a>
							</div>
							<ul class="footer-nav">
								<li><a href="#">Privacy Policy</a></li>
							</ul>
							<div class="footer-copyright">
								<span>
									&copy;Copyright &copy;
									<script>
										document.write(new Date().getFullYear());
									</script>
									All rights reserved
								</span>
							</div>
						</div>
					</div>

					<div class="col-md-4">
						<div class="row">
							<div class="col-md-6">
								<div class="footer-widget">
									<ul class="footer-links">
										<li><a href = "post.php"><strong>POSTS</strong></a></li>
										<li><a href = "reports.php"><strong>REPORTS</strong></a></li>
									</ul>
								</div>
							</div>
							<div class="col-md-6">
								<div class="footer-widget">
									<h3 class="footer-title">Catagories</h3>
									<ul class="footer-links">
										<li><a href="index.php">HOME</a></li>
										<li><a href="about.php">ABOUT US</a></li>
										<li><a href="contact.php">CONTACT US</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>

					<div class="col-md-3">
						<div class="footer-widget">
							<h3 class="footer-title">To receive our Newsletter</h3>
							<div class="footer-newsletter">
								<form action="https://app.moosend.com/subscribe/328a6603-5f61-4a05-bd0b-b17d6c9da0cc" method="post" id="ms-sub-form" target="_blank">
									<div>
									<label for="email">email:</label><input type="email" name="ms-email" id="email" class="input" required />
									<input type="submit" value="Subscribe" /><div style="margin-top: 10px;"><a href="//www.moosend.com/?utm_source=poweredby&utm_medium=forms&utm_campaign=elephantalert254.moosend.com" target="_blank"><img alt="powered by moosend" src="//www.moosend.com/images/poweredby.png" /></a></div>
									</div>
								</form>
							</div>
							<ul class="footer-social">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
							</ul>
						</div>
					</div>

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</footer>
		<!-- /Footer -->

		<!-- jQuery Plugins -->
		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/main.js"></script>
